### ISSUE TITLE
g tag is not working

### ISSUE THREAD

**Issue by Dekhnar** [aloisdeniel/path_icon#3]
Hello I'm getting a parsing error when i'm using g tag:

*`type 'XmlText' is not a subtype of type 'XmlElement'`*

example with (from: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g):
`<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <g>
    <circle cx="40" cy="40" r="25" />
    <circle cx="60" cy="60" r="25" />
  </g>
</svg>`

**Comment by aloisdeniel** [comment]
Thanks a lot for reporting! I found the issue, sorry about that.

I published a fix in the `0.6.4` version.
